### ISSUE TITLE
Create branches for Yocto, apply patches

### ISSUE THREAD

**Issue by EwanRoycroft** [bbc/linux#3]
Once https://github.com/bbc/px-yocto/issues/62 is applied, Yocto will track changes from this repo. Some changes should be made to this repo to incorporate changes into Yocto.

In a similar fashion to Chromium, we should have branches for different kernel versions with all changes applied for Yocto. For example, Yocto should currently be tracking from a branch named e.g. `rpi-5.10.82-yocto`. This branch should include e95b0e016123f6f1a74ea01a9efcb105e8c638b5. 

We should also commit the patches made by Yocto and apply them to the branch above:
1.  https://github.com/bbc/px-yocto/blob/master/meta-px/recipes-kernel/linux/files/0001-Add-config_store-to-videodev2.h.patch
2. https://github.com/bbc/px-yocto/blob/master/meta-px/recipes-kernel/linux/files/0001-Add-usr-include-linux-media.patch
3. https://github.com/bbc/px-yocto/blob/master/meta-px/recipes-kernel/linux/files/0002-Added-missing-licence-declaration.patch

**Comment by matt-hammond-001** [comment]
#62 is now applied.
